#!/usr/bin/env python3
"""
Build sanctoral calendar YAML from grc_sanctoral_data.py reference.

Writes:
  data/sv/calendars/general/entries.yaml
  data/en/calendars/general/entries.yaml
  data/sv/calendars/local/stockholm.yaml (additions/overrides preserved structure)

Usage:
  python scripts/build-sanctoral-calendars.py
  python scripts/build-sanctoral-calendars.py --dry-run
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("PyYAML required", file=sys.stderr)
    sys.exit(1)

from grc_sanctoral_data import (
    GRC_ENTRIES,
    STOCKHOLM_ADDITIONS,
    STOCKHOLM_OVERRIDES,
    SanctoralEntry,
)

REPO_ROOT = Path(__file__).resolve().parent.parent


def entry_to_yaml(e: SanctoralEntry, locale: str) -> dict:
    d: dict = {
        "id": e.id,
        "name": e.name_sv if locale == "sv" else e.name_en,
        "rank": e.rank,
        "calendar_position": {"type": "fixed", "month": e.month, "day": e.day},
        "applicable_commons": e.commons,
    }
    if e.observance_of:
        d["observance_of"] = e.observance_of
    if e.transfer_rule:
        d["transfer_rule"] = e.transfer_rule
    return d


def build_general(locale: str) -> dict:
    entries = [entry_to_yaml(e, locale) for e in GRC_ENTRIES]
    entries.sort(key=lambda x: (x["calendar_position"]["month"], x["calendar_position"]["day"], x["id"]))
    return {"entries": entries}


def build_stockholm(locale: str) -> dict:
    additions = [entry_to_yaml(e, locale) for e in STOCKHOLM_ADDITIONS]
    additions.sort(key=lambda x: (x["calendar_position"]["month"], x["calendar_position"]["day"], x["id"]))
    overrides = []
    for o in STOCKHOLM_OVERRIDES:
        patch = {"id": o["id"]}
        name_key = "name" if locale == "sv" else "name_en"
        if name_key in o:
            patch["name"] = o[name_key]
        if "rank" in o:
            patch["rank"] = o["rank"]
        overrides.append(patch)
    return {
        "calendar_id": "stockholm",
        "extends": "general",
        "seasonal_observance": {
            "epiphany": "fixed_jan_6",
            "corpus_christi": "second_sunday_after_pentecost",
            "ascension": "thursday",
        },
        "overrides": overrides,
        "additions": additions,
    }


def write_expected_manifest() -> None:
    """Reference manifest for check-ordo-calendar.mjs."""
    out_path = REPO_ROOT / "data" / "ordo" / "expected-calendar.yaml"
    entries = []
    for e in GRC_ENTRIES:
        entries.append({
            "id": e.id,
            "layer": "general",
            "rank": e.rank,
            "fixed_date": {"month": e.month, "day": e.day},
            "name_en": e.name_en,
        })
    for e in STOCKHOLM_ADDITIONS:
        entries.append({
            "id": e.id,
            "layer": "stockholm",
            "rank": e.rank,
            "fixed_date": {"month": e.month, "day": e.day},
            "name_en": e.name_en,
        })
    for o in STOCKHOLM_OVERRIDES:
        entries.append({
            "id": o["id"],
            "layer": "stockholm",
            "kind": "override",
            "rank": o.get("rank"),
        })
    doc = {"entries": entries}
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(
        yaml.dump(doc, allow_unicode=True, sort_keys=False, width=120),
        encoding="utf-8",
    )
    print(f"Writing {out_path} ({len(entries)} expected entries)")


def write_yaml(path: Path, data: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    header = "# Auto-generated by scripts/build-sanctoral-calendars.py — edit grc_sanctoral_data.py instead.\n"
    body = yaml.dump(data, allow_unicode=True, sort_keys=False, width=120, default_flow_style=False)
    path.write_text(header + body, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    targets = [
        (REPO_ROOT / "data" / "sv" / "calendars" / "general" / "entries.yaml", build_general("sv")),
        (REPO_ROOT / "data" / "en" / "calendars" / "general" / "entries.yaml", build_general("en")),
        (REPO_ROOT / "data" / "sv" / "calendars" / "local" / "stockholm.yaml", build_stockholm("sv")),
        (REPO_ROOT / "data" / "en" / "calendars" / "local" / "stockholm.yaml", build_stockholm("en")),
    ]

    for path, data in targets:
        count = len(data.get("entries", data.get("additions", [])))
        print(f"{'Would write' if args.dry_run else 'Writing'} {path} ({count} primary entries)")
        if not args.dry_run:
            write_yaml(path, data)

    if not args.dry_run:
        write_expected_manifest()

    print(f"GRC entries: {len(GRC_ENTRIES)}, Stockholm additions: {len(STOCKHOLM_ADDITIONS)}")


if __name__ == "__main__":
    main()
