"""
General Roman Calendar fixed-date sanctoral entries (2021+ revisions).
Source: General Roman Calendar as in Calendarium Romanum / Wikipedia GRC list.
Moveable temporal celebrations are excluded (handled in proper_of_seasons).
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class SanctoralEntry:
    id: str
    name_en: str
    name_sv: str
    month: int
    day: int
    rank: str  # solemnity | feast | obligatory_memoria | optional_memoria
    commons: list[str] = field(default_factory=list)
    observance_of: str | None = None  # "lord" for feasts of the Lord
    transfer_rule: str | None = None


# fmt: off
GRC_ENTRIES: list[SanctoralEntry] = [
    # January
    SanctoralEntry("basil_gregory_nazianzen", "Saints Basil the Great and Gregory Nazianzen, Bishops and Doctors of the Church", "S:t Basilios den store och S:t Gregorios av Nazianzos, biskopar och kyrkolärare", 1, 2, "obligatory_memoria", ["doctors"]),
    SanctoralEntry("holy_name_of_jesus", "The Most Holy Name of Jesus", "Det heliga namnet Jesus", 1, 3, "optional_memoria", []),
    SanctoralEntry("raymond_of_penyafort", "Saint Raymond of Penyafort, Priest", "S:t Raimund av Peñafort, präst", 1, 7, "optional_memoria", ["pastors"]),
    SanctoralEntry("hilary_of_poitiers", "Saint Hilary of Poitiers, Bishop and Doctor of the Church", "S:t Hilarius av Poitiers, biskop och kyrkolärare", 1, 13, "optional_memoria", ["doctors"]),
    SanctoralEntry("anthony_of_egypt", "Saint Anthony, Abbot", "S:t Antonius, abbot", 1, 17, "obligatory_memoria", ["holy_men_women"]),
    SanctoralEntry("fabian_pope", "Saint Fabian, Pope and Martyr", "S:t Fabianus, påve och martyr", 1, 20, "optional_memoria", ["martyrs", "pastors"]),
    SanctoralEntry("sebastian_martyr", "Saint Sebastian, Martyr", "S:t Sebastian, martyr", 1, 20, "optional_memoria", ["martyrs"]),
    SanctoralEntry("agnes_virgin", "Saint Agnes, Virgin and Martyr", "S:ta Agnes, jungfru och martyr", 1, 21, "obligatory_memoria", ["virgins", "martyrs"]),
    SanctoralEntry("vincent_of_saragossa", "Saint Vincent, Deacon and Martyr", "S:t Vincentius av Saragossa, diakon och martyr", 1, 22, "optional_memoria", ["martyrs"]),
    SanctoralEntry("francis_de_sales", "Saint Francis de Sales, Bishop and Doctor of the Church", "S:t François de Sales, biskop och kyrkolärare", 1, 24, "obligatory_memoria", ["doctors", "pastors"]),
    SanctoralEntry("conversion_of_paul", "The Conversion of Saint Paul the Apostle", "S:t Paulus omvändelse", 1, 25, "feast", ["apostles"]),
    SanctoralEntry("timothy_titus", "Saints Timothy and Titus, Bishops", "S:t Timotheos och S:t Titus, biskopar", 1, 26, "obligatory_memoria", ["pastors"]),
    SanctoralEntry("angela_merici", "Saint Angela Merici, Virgin", "S:ta Angela Merici, jungfru", 1, 27, "optional_memoria", ["virgins"]),
    SanctoralEntry("thomas_aquinas", "Saint Thomas Aquinas, Priest and Doctor of the Church", "S:t Thomas av Aquino, präst och kyrkolärare", 1, 28, "obligatory_memoria", ["doctors"]),
    SanctoralEntry("john_bosco", "Saint John Bosco, Priest", "S:t Johannes Bosco, präst", 1, 31, "obligatory_memoria", ["pastors", "holy_men_women"]),
    # February
    SanctoralEntry("presentation_of_the_lord", "The Presentation of the Lord", "Kyndelsmässodagen, Herrens frambärande i templet", 2, 2, "feast", ["bvm"], observance_of="lord"),
    SanctoralEntry("blaise_bishop", "Saint Blaise, Bishop and Martyr", "S:t Blasius, biskop och martyr", 2, 3, "optional_memoria", ["martyrs", "pastors"]),
    SanctoralEntry("agatha_virgin", "Saint Agatha, Virgin and Martyr", "S:ta Agatha, jungfru och martyr", 2, 5, "obligatory_memoria", ["virgins", "martyrs"]),
    SanctoralEntry("paul_miki_companions", "Saints Paul Miki and Companions, Martyrs", "S:t Paul Miki och hans följeslagare, martyrer", 2, 6, "obligatory_memoria", ["martyrs"]),
    SanctoralEntry("jerome_emiliani", "Saint Jerome Emiliani, Priest", "S:t Hieronymus Emiliani, präst", 2, 8, "optional_memoria", ["pastors", "holy_men_women"]),
    SanctoralEntry("josephine_bakhita", "Saint Josephine Bakhita, Virgin", "S:ta Josephine Bakhita, jungfru", 2, 8, "optional_memoria", ["virgins", "holy_men_women"]),
    SanctoralEntry("scholastica", "Saint Scholastica, Virgin", "S:ta Scholastica, jungfru", 2, 10, "obligatory_memoria", ["virgins"]),
    SanctoralEntry("our_lady_of_lourdes", "Our Lady of Lourdes", "Jungfru Maria av Lourdes", 2, 11, "optional_memoria", ["bvm"]),
    SanctoralEntry("cyril_methodius", "Saints Cyril, Monk, and Methodius, Bishop", "S:t Kyrillos, munk, och S:t Methodios, biskop, Europas skyddspatroner", 2, 14, "feast", ["doctors"]),
    SanctoralEntry("seven_holy_founders", "The Seven Holy Founders of the Servite Order", "De sju heliga grundarna av servitorden", 2, 17, "optional_memoria", ["holy_men_women"]),
    SanctoralEntry("peter_damian", "Saint Peter Damian, Bishop and Doctor of the Church", "S:t Petrus Damianus, biskop och kyrkolärare", 2, 21, "optional_memoria", ["doctors", "pastors"]),
    SanctoralEntry("peters_chair", "The Chair of Saint Peter the Apostle", "S:t Petrus biskopsstol", 2, 22, "feast", ["apostles"]),
    SanctoralEntry("polycarp_bishop", "Saint Polycarp, Bishop and Martyr", "S:t Polykarpos, biskop och martyr", 2, 23, "obligatory_memoria", ["martyrs", "pastors"]),
    SanctoralEntry("gregory_of_narek", "Saint Gregory of Narek, Abbot and Doctor of the Church", "S:t Gregorios av Narek, abbot och kyrkolärare", 2, 27, "optional_memoria", ["doctors", "holy_men_women"]),
    # March
    SanctoralEntry("casimir", "Saint Casimir", "S:t Casimir", 3, 4, "optional_memoria", ["holy_men_women"]),
    SanctoralEntry("perpetua_felicity", "Saints Perpetua and Felicity, Martyrs", "S:ta Perpetua och S:ta Felicitas, martyrer", 3, 7, "obligatory_memoria", ["martyrs"]),
    SanctoralEntry("john_of_god", "Saint John of God, Religious", "S:t Johannes av Gud, religiös", 3, 8, "optional_memoria", ["holy_men_women"]),
    SanctoralEntry("frances_of_rome", "Saint Frances of Rome, Religious", "S:ta Francesca av Rom, religiös", 3, 9, "optional_memoria", ["holy_men_women"]),
    SanctoralEntry("patrick_bishop", "Saint Patrick, Bishop", "S:t Patrick, biskop", 3, 17, "optional_memoria", ["pastors"]),
    SanctoralEntry("cyril_of_jerusalem", "Saint Cyril of Jerusalem, Bishop and Doctor of the Church", "S:t Kyrillos av Jerusalem, biskop och kyrkolärare", 3, 18, "optional_memoria", ["doctors", "pastors"]),
    SanctoralEntry("joseph_spouse_of_mary", "Saint Joseph, Spouse of the Blessed Virgin Mary", "S:t Josef, jungfru Marias brudgum", 3, 19, "solemnity", ["holy_men_women"]),
    SanctoralEntry("turibius_mongrovejo", "Saint Turibius of Mongrovejo, Bishop", "S:t Turibius av Mongrovejo, biskop", 3, 23, "optional_memoria", ["pastors"]),
    SanctoralEntry("annunciation", "The Annunciation of the Lord", "Herrens bebådelse – jungfru Marie bebådelsedag", 3, 25, "solemnity", ["bvm"], observance_of="lord", transfer_rule="annunciation_gnly60"),
    # April
    SanctoralEntry("francis_of_paola", "Saint Francis of Paola, Hermit", "S:t Franciscus av Paola, eremit", 4, 2, "optional_memoria", ["holy_men_women"]),
    SanctoralEntry("isidore_seville", "Saint Isidore, Bishop and Doctor of the Church", "S:t Isidor, biskop och kyrkolärare", 4, 4, "optional_memoria", ["doctors", "pastors"]),
    SanctoralEntry("vincent_ferrer", "Saint Vincent Ferrer, Priest", "S:t Vincent Ferrer, präst", 4, 5, "optional_memoria", ["pastors", "holy_men_women"]),
    SanctoralEntry("john_baptist_de_la_salle", "Saint John Baptist de la Salle, Priest", "S:t Johannes Baptiste de la Salle, präst", 4, 7, "obligatory_memoria", ["pastors", "holy_men_women"]),
    SanctoralEntry("stanislaus_bishop", "Saint Stanislaus, Bishop and Martyr", "S:t Stanislaus, biskop och martyr", 4, 11, "obligatory_memoria", ["martyrs", "pastors"]),
    SanctoralEntry("martin_i_pope", "Saint Martin I, Pope and Martyr", "S:t Martin I, påve och martyr", 4, 13, "optional_memoria", ["martyrs", "pastors"]),
    SanctoralEntry("anselm_canterbury", "Saint Anselm, Bishop and Doctor of the Church", "S:t Anselm av Canterbury, biskop och kyrkolärare", 4, 21, "optional_memoria", ["doctors", "pastors"]),
    SanctoralEntry("george_martyr", "Saint George, Martyr", "S:t Georg, martyr", 4, 23, "optional_memoria", ["martyrs"]),
    SanctoralEntry("adalbert_bishop", "Saint Adalbert, Bishop and Martyr", "S:t Adalbert, biskop och martyr", 4, 23, "optional_memoria", ["martyrs", "pastors"]),
    SanctoralEntry("fidelis_sigmaringen", "Saint Fidelis of Sigmaringen, Priest and Martyr", "S:t Fidelis av Sigmaringen, präst och martyr", 4, 24, "optional_memoria", ["martyrs", "pastors"]),
    SanctoralEntry("mark_evangelist", "Saint Mark, Evangelist", "S:t Markus, evangelist", 4, 25, "feast", ["apostles"]),
    SanctoralEntry("peter_chanel", "Saint Peter Chanel, Priest and Martyr", "S:t Petrus Chanel, präst och martyr", 4, 28, "optional_memoria", ["martyrs", "pastors"]),
    SanctoralEntry("louis_grignion_montfort", "Saint Louis Grignon de Montfort, Priest", "S:t Ludvig Maria Grignion de Montfort, präst", 4, 28, "optional_memoria", ["pastors", "holy_men_women"]),
    SanctoralEntry("catherine_of_siena", "Saint Catherine of Siena, Virgin and Doctor of the Church", "S:ta Katarina av Siena, jungfru och kyrkolärare, Europas skyddspatron", 4, 29, "feast", ["virgins", "doctors"]),
    SanctoralEntry("pius_v_pope", "Saint Pius V, Pope", "S:t Pius V, påve", 4, 30, "optional_memoria", ["pastors"]),
    # May
    SanctoralEntry("joseph_the_worker", "Saint Joseph the Worker", "S:t Josef arbetare", 5, 1, "optional_memoria", ["holy_men_women"]),
    SanctoralEntry("athanasius", "Saint Athanasius, Bishop and Doctor of the Church", "S:t Athanasios, biskop och kyrkolärare", 5, 2, "obligatory_memoria", ["doctors", "pastors"]),
    SanctoralEntry("philip_james_apostles", "Saints Philip and James, Apostles", "S:t Filippos och S:t Jakob, apostlar", 5, 3, "feast", ["apostles"]),
    SanctoralEntry("john_of_avila", "Saint John of Ávila, Priest and Doctor of the Church", "S:t Johannes av Ávila, präst och kyrkolärare", 5, 10, "optional_memoria", ["doctors", "pastors"]),
    SanctoralEntry("nereus_achilleus", "Saints Nereus and Achilleus, Martyrs", "S:t Nereus och S:t Achilleus, martyrer", 5, 12, "optional_memoria", ["martyrs"]),
    SanctoralEntry("pancras_martyr", "Saint Pancras, Martyr", "S:t Pancratius, martyr", 5, 12, "optional_memoria", ["martyrs"]),
    SanctoralEntry("our_lady_of_fatima", "Our Lady of Fatima", "Jungfru Maria av Fatima", 5, 13, "optional_memoria", ["bvm"]),
    SanctoralEntry("matthias_apostle", "Saint Matthias, Apostle", "S:t Mattias, apostel", 5, 14, "feast", ["apostles"]),
    SanctoralEntry("john_i_pope", "Saint John I, Pope and Martyr", "S:t Johannes I, påve och martyr", 5, 18, "optional_memoria", ["martyrs", "pastors"]),
    SanctoralEntry("bernardine_of_siena", "Saint Bernardine of Siena, Priest", "S:t Bernhardin av Siena, präst", 5, 20, "optional_memoria", ["pastors", "holy_men_women"]),
    SanctoralEntry("christopher_magallanes", "Saint Christopher Magallanes, Priest, and Companions, Martyrs", "S:t Christopher Magallanes, präst, och följeslagare, martyrer", 5, 21, "optional_memoria", ["martyrs", "pastors"]),
    SanctoralEntry("rita_of_cascia", "Saint Rita of Cascia, Religious", "S:ta Rita av Cascia, religiös", 5, 22, "optional_memoria", ["holy_men_women"]),
    SanctoralEntry("bede_venerable", "Saint Bede the Venerable, Priest and Doctor of the Church", "S:t Beda den vördnadsvärde, präst och kyrkolärare", 5, 25, "optional_memoria", ["doctors", "holy_men_women"]),
    SanctoralEntry("gregory_vii_pope", "Saint Gregory VII, Pope", "S:t Gregorius VII, påve", 5, 25, "optional_memoria", ["pastors"]),
    SanctoralEntry("mary_magdalene_de_pazzi", "Saint Mary Magdalene de' Pazzi, Virgin", "S:ta Maria Magdalena de' Pazzi, jungfru", 5, 25, "optional_memoria", ["virgins"]),
    SanctoralEntry("philip_neri", "Saint Philip Neri, Priest", "S:t Filip Neri, präst", 5, 26, "obligatory_memoria", ["pastors", "holy_men_women"]),
    SanctoralEntry("augustine_of_canterbury", "Saint Augustine of Canterbury, Bishop", "S:t Augustinus av Canterbury, biskop", 5, 27, "optional_memoria", ["pastors"]),
    SanctoralEntry("paul_vi", "Saint Paul VI, Pope", "S:t Paulus VI, påve", 5, 29, "optional_memoria", ["pastors"]),
    SanctoralEntry("visitation_of_mary", "The Visitation of the Blessed Virgin Mary", "Den saliga jungfru Marias besök", 5, 31, "feast", ["bvm"]),
    # June
    SanctoralEntry("justin_martyr", "Saint Justin, Martyr", "S:t Justin, martyr", 6, 1, "obligatory_memoria", ["martyrs"]),
    SanctoralEntry("marcellinus_peter", "Saints Marcellinus and Peter, Martyrs", "S:t Marcellinus och S:t Petrus, martyrer", 6, 2, "optional_memoria", ["martyrs"]),
    SanctoralEntry("charles_lwanga", "Saints Charles Lwanga and Companions, Martyrs", "S:t Charles Lwanga och hans följeslagare, martyrer", 6, 3, "obligatory_memoria", ["martyrs"]),
    SanctoralEntry("boniface_bishop", "Saint Boniface, Bishop and Martyr", "S:t Bonifatius, biskop och martyr", 6, 5, "obligatory_memoria", ["martyrs", "pastors"]),
    SanctoralEntry("norbert_bishop", "Saint Norbert, Bishop", "S:t Norbert, biskop", 6, 6, "optional_memoria", ["pastors"]),
    SanctoralEntry("ephrem_deacon", "Saint Ephrem, Deacon and Doctor of the Church", "S:t Efraim Syriern, diakon och kyrkolärare", 6, 9, "optional_memoria", ["doctors", "holy_men_women"]),
    SanctoralEntry("barnabas_apostle", "Saint Barnabas, Apostle", "S:t Barnabas, apostel", 6, 11, "obligatory_memoria", ["apostles"]),
    SanctoralEntry("anthony_of_padua", "Saint Anthony of Padua, Priest and Doctor of the Church", "S:t Antonius av Padua, präst och kyrkolärare", 6, 13, "obligatory_memoria", ["doctors", "pastors"]),
    SanctoralEntry("romuald_abbot", "Saint Romuald, Abbot", "S:t Romuald, abbot", 6, 19, "optional_memoria", ["holy_men_women"]),
    SanctoralEntry("aloysius_gonzaga", "Saint Aloysius Gonzaga, Religious", "S:t Aloisius Gonzaga, religiös", 6, 21, "obligatory_memoria", ["holy_men_women"]),
    SanctoralEntry("paulinus_of_nola", "Saint Paulinus of Nola, Bishop", "S:t Paulinus av Nola, biskop", 6, 22, "optional_memoria", ["pastors"]),
    SanctoralEntry("john_fisher_thomas_more", "Saints John Fisher, Bishop, and Thomas More, Martyrs", "S:t Johannes Fisher, biskop, och S:t Thomas More, martyrer", 6, 22, "optional_memoria", ["martyrs", "pastors"]),
    SanctoralEntry("john_baptist_nativity", "The Nativity of Saint John the Baptist", "S:t Johannes döparens födelse", 6, 24, "solemnity", []),
    SanctoralEntry("cyril_of_alexandria", "Saint Cyril of Alexandria, Bishop and Doctor of the Church", "S:t Kyrillos av Alexandria, biskop och kyrkolärare", 6, 27, "optional_memoria", ["doctors", "pastors"]),
    SanctoralEntry("irenaeus", "Saint Irenaeus, Bishop, Martyr and Doctor of the Church", "S:t Irenaeus, biskop, martyr och kyrkolärare", 6, 28, "obligatory_memoria", ["doctors", "martyrs", "pastors"]),
    SanctoralEntry("peter_paul_apostles", "Saints Peter and Paul, Apostles", "S:t Petrus och S:t Paulus, apostlar", 6, 29, "solemnity", ["apostles"]),
    SanctoralEntry("first_martyrs_rome", "The First Martyrs of the Holy Roman Church", "Romerska kyrkans första martyrer", 6, 30, "optional_memoria", ["martyrs"]),
    # July
    SanctoralEntry("thomas_apostle", "Saint Thomas, Apostle", "S:t Tomas, apostel", 7, 3, "feast", ["apostles"]),
    SanctoralEntry("elizabeth_of_portugal", "Saint Elizabeth of Portugal", "S:ta Elisabet av Portugal", 7, 4, "optional_memoria", ["holy_men_women"]),
    SanctoralEntry("anthony_zaccaria", "Saint Anthony Zaccaria, Priest", "S:t Antonius Zaccaria, präst", 7, 5, "optional_memoria", ["pastors"]),
    SanctoralEntry("maria_goretti", "Saint Maria Goretti, Virgin and Martyr", "S:ta Maria Goretti, jungfru och martyr", 7, 6, "optional_memoria", ["virgins", "martyrs"]),
    SanctoralEntry("augustine_zhao_companions", "Saint Augustine Zhao Rong, Priest, and Companions, Martyrs", "S:t Augustinus Zhao Rong, präst, och följeslagare, martyrer", 7, 9, "optional_memoria", ["martyrs", "pastors"]),
    SanctoralEntry("benedict_of_nursia", "Saint Benedict, Abbot", "S:t Benedictus av Nursia, abbot, Europas skyddspatron", 7, 11, "feast", ["doctors", "holy_men_women"]),
    SanctoralEntry("henry_emperor", "Saint Henry", "S:t Henrik", 7, 13, "optional_memoria", ["holy_men_women"]),
    SanctoralEntry("camillus_de_lellis", "Saint Camillus de Lellis, Priest", "S:t Camillus de Lellis, präst", 7, 14, "optional_memoria", ["pastors", "holy_men_women"]),
    SanctoralEntry("bonaventure", "Saint Bonaventure, Bishop and Doctor of the Church", "S:t Bonaventura, biskop och kyrkolärare", 7, 15, "obligatory_memoria", ["doctors", "pastors"]),
    SanctoralEntry("our_lady_of_mount_carmel", "Our Lady of Mount Carmel", "Jungfru Maria av berget Karmel", 7, 16, "optional_memoria", ["bvm"]),
    SanctoralEntry("apollinaris_bishop", "Saint Apollinaris, Bishop and Martyr", "S:t Apollinaris, biskop och martyr", 7, 20, "optional_memoria", ["martyrs", "pastors"]),
    SanctoralEntry("lawrence_of_brindisi", "Saint Lawrence of Brindisi, Priest and Doctor of the Church", "S:t Laurentius av Brindisi, präst och kyrkolärare", 7, 21, "optional_memoria", ["doctors", "pastors"]),
    SanctoralEntry("mary_magdalene", "Saint Mary Magdalene", "S:ta Maria från Magdala", 7, 22, "feast", ["holy_men_women"]),
    SanctoralEntry("st_birgitta", "Saint Bridget of Sweden, Religious", "S:ta Birgittas himmelska födelsedag", 7, 23, "feast", ["holy_men_women"]),
    SanctoralEntry("charbel_makhluf", "Saint Sharbel Makhluf, Priest", "S:t Charbel Makhluf, präst", 7, 24, "optional_memoria", ["pastors", "holy_men_women"]),
    SanctoralEntry("james_apostle", "Saint James, Apostle", "S:t Jakob, apostel", 7, 25, "feast", ["apostles"]),
    SanctoralEntry("joachim_anne", "Saints Joachim and Anne, Parents of the Blessed Virgin Mary", "S:t Joachim och S:ta Anna, jungfru Marias föräldrar", 7, 26, "obligatory_memoria", ["holy_men_women"]),
    SanctoralEntry("martha_mary_lazarus", "Saints Martha, Mary and Lazarus", "S:ta Marta, Maria och Lasarus", 7, 29, "obligatory_memoria", ["holy_men_women"]),
    SanctoralEntry("peter_chrysologus", "Saint Peter Chrysologus, Bishop and Doctor of the Church", "S:t Petrus Chrysologus, biskop och kyrkolärare", 7, 30, "optional_memoria", ["doctors", "pastors"]),
    SanctoralEntry("ignatius_of_loyola", "Saint Ignatius of Loyola, Priest", "S:t Ignatius av Loyola, präst", 7, 31, "obligatory_memoria", ["pastors", "holy_men_women"]),
    # August
    SanctoralEntry("alphonsus_liguori", "Saint Alphonsus Liguori, Bishop and Doctor of the Church", "S:t Alphonsus Liguori, biskop och kyrkolärare", 8, 1, "obligatory_memoria", ["doctors", "pastors"]),
    SanctoralEntry("eusebius_vercelli", "Saint Eusebius of Vercelli, Bishop", "S:t Eusebius av Vercelli, biskop", 8, 2, "optional_memoria", ["pastors"]),
    SanctoralEntry("peter_julian_eymard", "Saint Peter Julian Eymard, Priest", "S:t Peter Julian Eymard, präst", 8, 2, "optional_memoria", ["pastors", "holy_men_women"]),
    SanctoralEntry("john_vianney", "Saint Jean Vianney, Priest", "S:t Jean Vianney, präst", 8, 4, "obligatory_memoria", ["pastors"]),
    SanctoralEntry("dedication_st_mary_major", "The Dedication of the Basilica of Saint Mary Major", "Basilikan S:t Maria Majors invigning", 8, 5, "optional_memoria", ["dedication_of_a_church", "bvm"]),
    SanctoralEntry("transfiguration_of_the_lord", "The Transfiguration of the Lord", "Kristi förklaring", 8, 6, "feast", [], observance_of="lord"),
    SanctoralEntry("sixtus_ii_companions", "Saint Sixtus II, Pope, and Companions, Martyrs", "S:t Sixtus II, påve, och följeslagare, martyrer", 8, 7, "optional_memoria", ["martyrs", "pastors"]),
    SanctoralEntry("cajetan_priest", "Saint Cajetan, Priest", "S:t Cajetanus, präst", 8, 7, "optional_memoria", ["pastors"]),
    SanctoralEntry("dominic_priest", "Saint Dominic, Priest", "S:t Dominicus, präst", 8, 8, "obligatory_memoria", ["pastors", "holy_men_women"]),
    SanctoralEntry("teresa_benedicta_of_the_cross", "Saint Teresa Benedicta of the Cross, Virgin and Martyr", "S:ta Teresia Benedicta av Korset", 8, 9, "feast", ["virgins", "doctors"]),
    SanctoralEntry("lawrence_deacon", "Saint Lawrence, Deacon and Martyr", "S:t Laurentius, diakon och martyr", 8, 10, "feast", ["martyrs"]),
    SanctoralEntry("clare_virgin", "Saint Clare, Virgin", "S:ta Clara, jungfru", 8, 11, "obligatory_memoria", ["virgins"]),
    SanctoralEntry("jane_frances_de_chantal", "Saint Jane Frances de Chantal, Religious", "S:ta Jane Frances de Chantal, religiös", 8, 12, "optional_memoria", ["holy_men_women"]),
    SanctoralEntry("pontian_hippolytus", "Saints Pontian, Pope, and Hippolytus, Priest, Martyrs", "S:t Pontianus, påve, och S:t Hippolytos, präst, martyrer", 8, 13, "optional_memoria", ["martyrs", "pastors"]),
    SanctoralEntry("maximus_confessor", "Saint Maximus the Confessor", "S:t Maximus Bekännaren", 8, 13, "optional_memoria", ["doctors", "holy_men_women"]),
    SanctoralEntry("maximilian_kolbe", "Saint Maximilian Kolbe, Priest and Martyr", "S:t Maximilian Kolbe, präst och martyr", 8, 14, "obligatory_memoria", ["martyrs", "pastors"]),
    SanctoralEntry("assumption_of_mary", "The Assumption of the Blessed Virgin Mary", "Jungfru Marias upptagning till himlen", 8, 15, "solemnity", ["bvm"]),
    SanctoralEntry("stephen_of_hungary", "Saint Stephen of Hungary", "S:t Stefan av Ungern", 8, 16, "optional_memoria", ["holy_men_women"]),
    SanctoralEntry("john_eudes", "Saint John Eudes, Priest", "S:t Johannes Eudes, präst", 8, 19, "optional_memoria", ["pastors"]),
    SanctoralEntry("bernard_of_clairvaux", "Saint Bernard, Abbot and Doctor of the Church", "S:t Bernhard, abbot och kyrkolärare", 8, 20, "obligatory_memoria", ["doctors", "holy_men_women"]),
    SanctoralEntry("pius_x_pope", "Saint Pius X, Pope", "S:t Pius X, påve", 8, 21, "obligatory_memoria", ["pastors"]),
    SanctoralEntry("queenship_of_mary", "The Queenship of the Blessed Virgin Mary", "Jungfru Marias drottningavtitel", 8, 22, "obligatory_memoria", ["bvm"]),
    SanctoralEntry("rose_of_lima", "Saint Rose of Lima, Virgin", "S:ta Rosa av Lima, jungfru", 8, 23, "optional_memoria", ["virgins"]),
    SanctoralEntry("bartholomew_apostle", "Saint Bartholomew, Apostle", "S:t Bartolomäus, apostel", 8, 24, "feast", ["apostles"]),
    SanctoralEntry("louis_king", "Saint Louis", "S:t Ludvig", 8, 25, "optional_memoria", ["holy_men_women"]),
    SanctoralEntry("joseph_calasanz", "Saint Joseph Calasanz, Priest", "S:t Joseph Calasanz, präst", 8, 25, "optional_memoria", ["pastors", "holy_men_women"]),
    SanctoralEntry("monica", "Saint Monica", "S:ta Monica", 8, 27, "obligatory_memoria", ["holy_men_women"]),
    SanctoralEntry("augustine_of_hippo", "Saint Augustine of Hippo, Bishop and Doctor of the Church", "S:t Augustinus, biskop och kyrkolärare", 8, 28, "obligatory_memoria", ["doctors", "pastors"]),
    SanctoralEntry("passion_of_john_baptist", "The Passion of Saint John the Baptist, Martyr", "S:t Johannes döparens lidande", 8, 29, "obligatory_memoria", ["martyrs"]),
    # September
    SanctoralEntry("gregory_the_great", "Saint Gregory the Great, Pope and Doctor of the Church", "S:t Gregorius den store, påve och kyrkolärare", 9, 3, "obligatory_memoria", ["doctors", "pastors"]),
    SanctoralEntry("teresa_of_calcutta", "Saint Teresa of Calcutta, Virgin", "S:ta Teresa av Calcutta, jungfru", 9, 5, "optional_memoria", ["virgins", "holy_men_women"]),
    SanctoralEntry("nativity_of_mary", "The Nativity of the Blessed Virgin Mary", "Den saliga jungfru Marias födelse", 9, 8, "feast", ["bvm"]),
    SanctoralEntry("peter_claver", "Saint Peter Claver, Priest", "S:t Peter Claver, präst", 9, 9, "optional_memoria", ["pastors", "holy_men_women"]),
    SanctoralEntry("holy_name_of_mary", "The Most Holy Name of Mary", "Jungfru Marias heliga namn", 9, 12, "optional_memoria", ["bvm"]),
    SanctoralEntry("john_chrysostom", "Saint John Chrysostom, Bishop and Doctor of the Church", "S:t Johannes Chrysostomos, biskop och kyrkolärare", 9, 13, "obligatory_memoria", ["doctors", "pastors"]),
    SanctoralEntry("exaltation_of_holy_cross", "The Exaltation of the Holy Cross", "Det heliga korsets upphöjelse", 9, 14, "feast", [], observance_of="lord"),
    SanctoralEntry("our_lady_of_sorrows", "Our Lady of Sorrows", "Jungfru Maria smärtornas moder", 9, 15, "obligatory_memoria", ["bvm"]),
    SanctoralEntry("cornelius_cyprian", "Saints Cornelius, Pope, and Cyprian, Bishop, Martyrs", "S:t Cornelius, påve, och S:t Cyprianus, biskop, martyrer", 9, 16, "obligatory_memoria", ["martyrs", "pastors"]),
    SanctoralEntry("robert_bellarmine", "Saint Robert Bellarmine, Bishop and Doctor of the Church", "S:t Robert Bellarmine, biskop och kyrkolärare", 9, 17, "optional_memoria", ["doctors", "pastors"]),
    SanctoralEntry("hildegard_of_bingen", "Saint Hildegard of Bingen, Virgin and Doctor of the Church", "S:ta Hildegard av Bingen, jungfru och kyrkolärare", 9, 17, "optional_memoria", ["virgins", "doctors"]),
    SanctoralEntry("januarius_bishop", "Saint Januarius, Bishop and Martyr", "S:t Januarius, biskop och martyr", 9, 19, "optional_memoria", ["martyrs", "pastors"]),
    SanctoralEntry("andrew_kim_companions", "Saints Andrew Kim Tae-gon, Priest, Paul Chong Ha-sang, and Companions, Martyrs", "S:t Andreas Kim Taegon, präst, Paulus Chong Hasang och följeslagare, martyrer", 9, 20, "obligatory_memoria", ["martyrs", "pastors"]),
    SanctoralEntry("matthew_apostle", "Saint Matthew, Apostle and Evangelist", "S:t Matteus, apostel", 9, 21, "feast", ["apostles"]),
    SanctoralEntry("pius_of_pietrelcina", "Saint Pius of Pietrelcina, Priest", "S:t Pius av Pietrelcina, präst", 9, 23, "obligatory_memoria", ["pastors", "holy_men_women"]),
    SanctoralEntry("cosmas_damian", "Saints Cosmas and Damian, Martyrs", "S:t Cosmas och S:t Damianus, martyrer", 9, 26, "optional_memoria", ["martyrs"]),
    SanctoralEntry("vincent_de_paul", "Saint Vincent de Paul, Priest", "S:t Vincent de Paul, präst", 9, 27, "obligatory_memoria", ["pastors", "holy_men_women"]),
    SanctoralEntry("wenceslaus_martyr", "Saint Wenceslaus, Martyr", "S:t Wenceslaus, martyr", 9, 28, "optional_memoria", ["martyrs"]),
    SanctoralEntry("lawrence_ruiz_companions", "Saint Lawrence Ruiz and Companions, Martyrs", "S:t Laurentius Ruiz och följeslagare, martyrer", 9, 28, "optional_memoria", ["martyrs"]),
    SanctoralEntry("michael_gabriel_raphael", "Saints Michael, Gabriel and Raphael, Archangels", "S:t Mikael, S:t Gabriel och S:t Rafael, ärkeänglar", 9, 29, "feast", []),
    SanctoralEntry("jerome_priest", "Saint Jerome, Priest and Doctor of the Church", "S:t Hieronymus, präst och kyrkolärare", 9, 30, "obligatory_memoria", ["doctors", "pastors"]),
    # October
    SanctoralEntry("therese_of_lisieux", "Saint Thérèse of the Child Jesus, Virgin and Doctor of the Church", "S:ta Teresa av Jesusbarnet, jungfru och kyrkolärare", 10, 1, "obligatory_memoria", ["virgins", "doctors"]),
    SanctoralEntry("guardian_angels", "The Holy Guardian Angels", "De heliga skyddsänglarna", 10, 2, "obligatory_memoria", []),
    SanctoralEntry("francis_of_assisi", "Saint Francis of Assisi", "S:t Franciscus av Assisi", 10, 4, "obligatory_memoria", ["holy_men_women"]),
    SanctoralEntry("faustina_kowalska", "Saint Faustina Kowalska, Virgin", "S:ta Faustina Kowalska, jungfru", 10, 5, "optional_memoria", ["virgins"]),
    SanctoralEntry("bruno_priest", "Saint Bruno, Priest", "S:t Bruno, präst", 10, 6, "optional_memoria", ["pastors", "holy_men_women"]),
    SanctoralEntry("our_lady_of_rosary", "Our Lady of the Rosary", "Jungfru Maria av Rosenkransen", 10, 7, "obligatory_memoria", ["bvm"]),
    SanctoralEntry("denis_companions", "Saint Denis, Bishop, and Companions, Martyrs", "S:t Dionysios, biskop, och följeslagare, martyrer", 10, 9, "optional_memoria", ["martyrs", "pastors"]),
    SanctoralEntry("john_leonardi", "Saint John Leonardi, Priest", "S:t Johannes Leonardi, präst", 10, 9, "optional_memoria", ["pastors"]),
    SanctoralEntry("john_xxiii", "Saint John XXIII, Pope", "S:t Johannes XXIII, påve", 10, 11, "optional_memoria", ["pastors"]),
    SanctoralEntry("callistus_i", "Saint Callistus I, Pope and Martyr", "S:t Callistus I, påve och martyr", 10, 14, "optional_memoria", ["martyrs", "pastors"]),
    SanctoralEntry("teresa_of_avila", "Saint Teresa of Jesus, Virgin and Doctor of the Church", "S:ta Teresa av Avila, jungfru och kyrkolärare", 10, 15, "obligatory_memoria", ["virgins", "doctors"]),
    SanctoralEntry("hedwig_religious", "Saint Hedwig, Religious", "S:ta Hedwig, religiös", 10, 16, "optional_memoria", ["holy_men_women"]),
    SanctoralEntry("margaret_mary_alacoque", "Saint Margaret Mary Alacoque, Virgin", "S:ta Margaret Mary Alacoque, jungfru", 10, 16, "optional_memoria", ["virgins"]),
    SanctoralEntry("ignatius_of_antioch", "Saint Ignatius of Antioch, Bishop and Martyr", "S:t Ignatius av Antiochia, biskop och martyr", 10, 17, "obligatory_memoria", ["martyrs", "pastors"]),
    SanctoralEntry("luke_evangelist", "Saint Luke, Evangelist", "S:t Lukas, evangelist", 10, 18, "feast", ["apostles"]),
    SanctoralEntry("north_american_martyrs", "Saints John de Brébeuf, Isaac Jogues, Priests, and Companions, Martyrs", "S:t Johannes de Brébeuf, Isaac Jogues, präster, och följeslagare, martyrer", 10, 19, "optional_memoria", ["martyrs", "pastors"]),
    SanctoralEntry("paul_of_the_cross", "Saint Paul of the Cross, Priest", "S:t Paulus av Korset, präst", 10, 19, "optional_memoria", ["pastors", "holy_men_women"]),
    SanctoralEntry("john_paul_ii", "Saint John Paul II, Pope", "S:t Johannes Paulus II, påve", 10, 22, "optional_memoria", ["pastors"]),
    SanctoralEntry("john_of_capistrano", "Saint John of Capistrano, Priest", "S:t Johannes av Capistrano, präst", 10, 23, "optional_memoria", ["pastors", "holy_men_women"]),
    SanctoralEntry("anthony_mary_claret", "Saint Anthony Mary Claret, Bishop", "S:t Antonius Maria Claret, biskop", 10, 24, "optional_memoria", ["pastors"]),
    SanctoralEntry("simon_jude_apostles", "Saints Simon and Jude, Apostles", "S:t Simon och S:t Judas, apostlar", 10, 28, "feast", ["apostles"]),
    # November
    SanctoralEntry("all_saints", "All Saints", "Alla helgons dag", 11, 1, "solemnity", []),
    SanctoralEntry("martin_de_porres", "Saint Martin de Porres, Religious", "S:t Martin de Porres, religiös", 11, 3, "optional_memoria", ["holy_men_women"]),
    SanctoralEntry("charles_borromeo", "Saint Charles Borromeo, Bishop", "S:t Carlo Borromeo, biskop", 11, 4, "obligatory_memoria", ["pastors"]),
    SanctoralEntry("dedication_lateran", "The Dedication of the Lateran Basilica", "Lateranbasilikans invigning", 11, 9, "feast", ["dedication_of_a_church"]),
    SanctoralEntry("leo_the_great", "Saint Leo the Great, Pope and Doctor of the Church", "S:t Leo den store, påve och kyrkolärare", 11, 10, "obligatory_memoria", ["doctors", "pastors"]),
    SanctoralEntry("martin_of_tours", "Saint Martin of Tours, Bishop", "S:t Martin av Tours, biskop", 11, 11, "obligatory_memoria", ["pastors"]),
    SanctoralEntry("josaphat_bishop", "Saint Josaphat, Bishop and Martyr", "S:t Josaphat, biskop och martyr", 11, 12, "obligatory_memoria", ["martyrs", "pastors"]),
    SanctoralEntry("albert_the_great", "Saint Albert the Great, Bishop and Doctor of the Church", "S:t Albertus Magnus, biskop och kyrkolärare", 11, 15, "optional_memoria", ["doctors", "pastors"]),
    SanctoralEntry("margaret_of_scotland", "Saint Margaret of Scotland", "S:ta Margaret av Skottland", 11, 16, "optional_memoria", ["holy_men_women"]),
    SanctoralEntry("gertrude_virgin", "Saint Gertrude, Virgin", "S:ta Gertrud, jungfru", 11, 16, "optional_memoria", ["virgins"]),
    SanctoralEntry("elizabeth_of_hungary", "Saint Elizabeth of Hungary, Religious", "S:ta Elisabet av Ungern, religiös", 11, 17, "obligatory_memoria", ["holy_men_women"]),
    SanctoralEntry("dedication_sts_peter_paul", "The Dedication of the Basilicas of Saints Peter and Paul, Apostles", "Basilikorna S:t Petrus och S:t Paulus invigning", 11, 18, "optional_memoria", ["dedication_of_a_church", "apostles"]),
    SanctoralEntry("presentation_of_mary", "The Presentation of the Blessed Virgin Mary", "Jungfru Marias tempelgång", 11, 21, "obligatory_memoria", ["bvm"]),
    SanctoralEntry("cecilia_virgin", "Saint Cecilia, Virgin and Martyr", "S:ta Cecilia, jungfru och martyr", 11, 22, "obligatory_memoria", ["virgins", "martyrs"]),
    SanctoralEntry("clement_i_pope", "Saint Clement I, Pope and Martyr", "S:t Clemens I, påve och martyr", 11, 23, "optional_memoria", ["martyrs", "pastors"]),
    SanctoralEntry("columban_abbot", "Saint Columban, Abbot", "S:t Columbanus, abbot", 11, 23, "optional_memoria", ["holy_men_women"]),
    SanctoralEntry("andrew_dung_lac", "Saints Andrew Dung-Lac, Priest, and Companions, Martyrs", "S:t Andreas Dung-Lac, präst, och följeslagare, martyrer", 11, 24, "obligatory_memoria", ["martyrs", "pastors"]),
    SanctoralEntry("catherine_of_alexandria", "Saint Catherine of Alexandria, Virgin and Martyr", "S:ta Katarina av Alexandria, jungfru och martyr", 11, 25, "optional_memoria", ["virgins", "martyrs"]),
    SanctoralEntry("andrew_apostle", "Saint Andrew, Apostle", "S:t Andreas, apostel", 11, 30, "feast", ["apostles"]),
    # December
    SanctoralEntry("francis_xavier", "Saint Francis Xavier, Priest", "S:t Francisco Xavier, präst", 12, 3, "obligatory_memoria", ["pastors", "holy_men_women"]),
    SanctoralEntry("john_damascene", "Saint John Damascene, Priest and Doctor of the Church", "S:t Johannes av Damaskus, präst och kyrkolärare", 12, 4, "optional_memoria", ["doctors", "pastors"]),
    SanctoralEntry("nicholas_bishop", "Saint Nicholas, Bishop", "S:t Nicolaus, biskop", 12, 6, "optional_memoria", ["pastors"]),
    SanctoralEntry("ambrose_bishop", "Saint Ambrose, Bishop and Doctor of the Church", "S:t Ambrosius, biskop och kyrkolärare", 12, 7, "obligatory_memoria", ["doctors", "pastors"]),
    SanctoralEntry("immaculate_conception", "The Immaculate Conception of the Blessed Virgin Mary", "Jungfru Marias utkorelse och fullkomliga renhet", 12, 8, "solemnity", ["bvm"]),
    SanctoralEntry("juan_diego", "Saint Juan Diego Cuauhtlatoatzin", "S:t Juan Diego", 12, 9, "optional_memoria", ["holy_men_women"]),
    SanctoralEntry("our_lady_of_loreto", "Our Lady of Loreto", "Jungfru Maria av Loreto", 12, 10, "optional_memoria", ["bvm"]),
    SanctoralEntry("damasus_i", "Saint Damasus I, Pope", "S:t Damasus I, påve", 12, 11, "optional_memoria", ["pastors"]),
    SanctoralEntry("our_lady_of_guadalupe", "Our Lady of Guadalupe", "Jungfru Maria av Guadalupe", 12, 12, "optional_memoria", ["bvm"]),
    SanctoralEntry("lucy_virgin", "Saint Lucy, Virgin and Martyr", "S:ta Lucia, jungfru och martyr", 12, 13, "obligatory_memoria", ["virgins", "martyrs"]),
    SanctoralEntry("john_of_the_cross", "Saint John of the Cross, Priest and Doctor of the Church", "S:t Johannes av Korset, präst och kyrkolärare", 12, 14, "obligatory_memoria", ["doctors", "pastors"]),
    SanctoralEntry("peter_canisius", "Saint Peter Canisius, Priest and Doctor of the Church", "S:t Petrus Canisius, präst och kyrkolärare", 12, 21, "optional_memoria", ["doctors", "pastors"]),
    SanctoralEntry("john_of_kanty", "Saint John of Kanty, Priest", "S:t Johannes av Kêty, präst", 12, 23, "optional_memoria", ["pastors"]),
    SanctoralEntry("stephen_proto_martyr", "Saint Stephen, the First Martyr", "S:t Stefanos, den förste martyren", 12, 26, "feast", ["martyrs"]),
    SanctoralEntry("john_apostle_evangelist", "Saint John, Apostle and Evangelist", "S:t Johannes, apostel och evangelist", 12, 27, "feast", ["apostles"]),
    SanctoralEntry("holy_innocents", "The Holy Innocents, Martyrs", "De heliga oskyldiga barnen i Betlehem", 12, 28, "feast", ["martyrs"]),
    SanctoralEntry("thomas_becket", "Saint Thomas Becket, Bishop and Martyr", "S:t Thomas Becket, biskop och martyr", 12, 29, "optional_memoria", ["martyrs", "pastors"]),
    SanctoralEntry("sylvester_i", "Saint Sylvester I, Pope", "S:t Silvester I, påve", 12, 31, "optional_memoria", ["pastors"]),
]
# fmt: on

# Stockholm diocese particular calendar (additions not in GRC, or not at this date/rank).
STOCKHOLM_ADDITIONS: list[SanctoralEntry] = [
    SanctoralEntry("st_henrik", "Saint Henrik, Bishop and Martyr", "S:t Henrik, biskop och martyr", 1, 19, "obligatory_memoria", ["pastors", "martyrs"]),
    SanctoralEntry("ansgar", "Saint Ansgar, Bishop, Apostle of the North", "S:t Ansgar, biskop, Nordens apostel", 2, 3, "obligatory_memoria", ["pastors"]),
    SanctoralEntry("nils_hermansson", "Blessed Nils Hermansson, Bishop", "S:t Nils Hermansson, biskop", 2, 4, "optional_memoria", ["pastors"]),
    SanctoralEntry("sigfrid_of_vaxjo", "Saint Sigfrid of Växjö, Bishop", "S:t Sigfrid av Växjö, biskop", 2, 15, "obligatory_memoria", ["pastors"]),
    SanctoralEntry("hemming_of_abo", "Blessed Hemming of Åbo, Bishop", "S:t Hemming av Åbo, biskop", 5, 21, "optional_memoria", ["pastors"]),
    SanctoralEntry("maria_elisabeth_hesselblad", "Saint Maria Elisabeth Hesselblad, Religious", "S:ta Maria Elisabeth Hesselblad, religiös", 6, 4, "obligatory_memoria", ["holy_men_women"]),
    SanctoralEntry("david_of_munktorp", "Saint David of Munktorp, Abbot", "S:t David av Munktorp, abbot", 6, 25, "optional_memoria", ["holy_men_women"]),
    SanctoralEntry("st_erik", "Saint Erik, King and Martyr, Patron of Sweden", "S:t Erik, konung och martyr", 5, 18, "feast", ["martyrs"]),
    SanctoralEntry("knud_martyr", "Saint Knud, Martyr, Patron of Denmark", "S:t Knut, martyr, Danmarks skyddspatron", 7, 10, "obligatory_memoria", ["martyrs"]),
    SanctoralEntry("thorlak_bishop", "Saint Thorlak, Bishop, Patron of Iceland", "S:t Thorlak, biskop, Islands skyddspatron", 7, 20, "obligatory_memoria", ["pastors"]),
    SanctoralEntry("botvid_martyr", "Saint Botvid, Martyr", "S:t Botvid, martyr", 7, 28, "optional_memoria", ["martyrs"]),
    SanctoralEntry("olav_martyr", "Saint Olav, King and Martyr, Patron of Norway", "S:t Olav, konung och martyr, Norges skyddspatron", 7, 29, "obligatory_memoria", ["martyrs"]),
    SanctoralEntry("elin_of_skovde", "Saint Elin of Skövde, Martyr", "S:ta Elin av Skövde, martyr", 7, 30, "optional_memoria", ["martyrs", "virgins"]),
    SanctoralEntry("katarina_of_vadstena", "Saint Catherine of Vadstena, Virgin", "S:ta Katarina av Vadstena, jungfru", 8, 2, "optional_memoria", ["virgins"]),
    SanctoralEntry("brynolf_of_skara", "Saint Brynolf of Skara, Bishop", "S:t Brynolf av Skara, biskop", 8, 16, "optional_memoria", ["pastors"]),
    SanctoralEntry("st_birgitta_patron", "Saint Birgitta of Sweden, Patron of Sweden and Europe", "S:ta Birgitta, Sveriges och Europas skyddspatron", 10, 7, "solemnity", ["holy_men_women"]),
    SanctoralEntry("ingrid_of_skenninge", "Saint Ingrid of Skänninge, Religious", "S:ta Ingrid av Skänninge, religiös", 10, 9, "optional_memoria", ["holy_men_women"]),
    SanctoralEntry("niels_stensen", "Blessed Niels Stensen, Bishop", "S:t Niels Stensen, biskop", 11, 25, "optional_memoria", ["pastors"]),
]

# Stockholm overrides on universal entries (same id, patched fields).
STOCKHOLM_OVERRIDES: list[dict] = [
    {
        "id": "st_birgitta",
        "name": "S:ta Birgittas himmelska födelsedag",
        "name_en": "Heavenly birthday of Saint Birgitta of Sweden",
        "rank": "optional_memoria",
    },
]

# GRC has Ansgar as optional on Feb 3; Stockholm elevates to obligatory — handled via
# stockholm addition with same date (addition wins if we suppress GRC optional).
STOCKHOLM_SUPPRESSIONS: list[str] = []  # ansgar not in GRC as separate id — GRC has no ansgar entry
